SHEET_NAME = "lista"
CELL_NAME = "buscar"
CELL_BM_NAME = "sampleid (bm code)"
CELL_HC_NAME= "esquimot code"
CELL_SAMPLE_NAME = "sample type"
CELL_NG_NAME = "ng/ul e"
CELL_BIS_NAME = "bm code bis"
EXTRACTION_FIRST = 1
NO_NAME = "-11"
NO_VOL = -1
POC_NAME = "poc"